service: powercontrol-proxy

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: prod
  timeout: 29 # 🚀 INYECCIÓN CRÍTICA: Le damos 29 segundos para procesar el Dashboard

functions:
  api:
    handler: server.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization