service: powercontrol-proxy

provider:
  name: aws
  runtime: nodejs20.x # Entorno Node de AWS
  region: us-east-1
  stage: prod

functions:
  api:
    handler: server.handler # Apunta al 'module.exports.handler' de tu server.js
    events:
      # Captura todas las subrutas (/api/alerts, /api/auth, etc.)
      - http:
          path: /{proxy+}
          method: ANY
      # Captura la ruta raíz (/)
      - http:
          path: /
          method: ANY